targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/features/market/models/*.dart
      json_serializable:
        generate_for:
          - lib/features/market/models/*.dart
      riverpod_generator:
        enabled: false
